<a href="https://colab.research.google.com/github/SusaiIgnesh/Readme/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#The first thing we want to do is import numpy.
import numpy as np

In [3]:
#Let us first define a Python list containing the ages of 6 people
ages_list = [10, 5, 8, 32, 65, 43]
print(ages_list)

[10, 5, 8, 32, 65, 43]


In [4]:
#There are 3 main ways to instantiate a Numpy ndarray object. One of these is to use np.array(<collection>)
ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [10]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

[10  5  8 32 65 43]
Size:	 6
Shape:	 (6,)


In [11]:
zeroArr = np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


**Multi-dime**

Now let us define a new list containing the weights of these 6 people.

In [12]:
#Now let us define a new list containing the weights of these 6 people
weight_list = [32, 18, 26, 60, 55, 65]

In [13]:
#Now, we define an ndarray containing all for this information, and again print the size and shape of the array.
people = np.array([ages_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)


People:	 [[10  5  8 32 65 43]
 [32 18 26 60 55 65]]
Size:	 12
Shape:	 (2, 6)


In [18]:
# 2 X 6 = 1 X 12 = 4 X 3 = 3 X 4 = 12 X 1

people = people.reshape(12,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10]
 [ 5]
 [ 8]
 [32]
 [65]
 [43]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]
Size:	 12
Shape:	 (12, 1)


Note: The new shape must be the same "size" as the old shape

**Exercise**-1

In [20]:
#Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]
list1=[7,9,65,33,85,99]
print(list1)


[7, 9, 65, 33, 85, 99]


In [21]:
#Generate a matrix (2D numpy array) of the values:

sam2=np.array([[1,2,4], [2,3,0],[0,5,1]])
sam2
print("sam2:\t" , sam2)
print("Size:\t" , sam2.size)
print("Shape:\t", sam2.shape)

sam2:	 [[1 2 4]
 [2 3 0]
 [0 5 1]]
Size:	 9
Shape:	 (3, 3)


In [57]:
# Change the dimensions of this array to another permitted shape
sam2 = sam2.reshape(1,9)

print("sam2:\t" , sam2)
print("Size:\t" , sam2.size)
print("Shape:\t", sam2.shape)

sam2:	 [[1 2 4 2 3 0 0 5 1]]
Size:	 9
Shape:	 (1, 9)


**Array Generation**

Instead of defining an array manually, we can ask numpy to do it for us.


The np.arange() method creates a range of numbers with user defined steps between each.

In [34]:
five_times_table = np.arange(0, 500, 50)
five_times_table

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

The np.linspace() method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [37]:
five_spaced = np.linspace(0,50,12)
print(five_spaced)

[ 0.          4.54545455  9.09090909 13.63636364 18.18181818 22.72727273
 27.27272727 31.81818182 36.36363636 40.90909091 45.45454545 50.        ]


The .repeat() method will repeat an object you pass a specified number of times.

In [39]:
fiveArr = np.repeat(5, 10)
print(fiveArr)

[5 5 5 5 5 5 5 5 5 5]


The np.eye() functions will create an identity matrix/array for us.

In [41]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Operations**


There are many, many operations which we can perform on arrays. Below, we demonstrate a few.


What is happening in each line?

In [42]:
five_times_table

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

In [47]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table <= 200)

1: [  0 100 200 300 400 500 600 700 800 900]
2: [ 10  60 110 160 210 260 310 360 410 460]
3: [ -1  49  99 149 199 249 299 349 399 449]
4: [ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
5: [     0   2500  10000  22500  40000  62500  90000 122500 160000 202500]
6: [ True  True  True  True  True False False False False False]


**Speed Test**


If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference.

In [50]:
fives_list = list(range(0,5001,5))
fives_list

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [52]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [53]:
#This module provides a simple way to find the execution time of small bits of Python code.

%timeit five_times_table_lge + 5

1.33 µs ± 36.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [54]:
%timeit [e + 5 for e in fives_list]

54.6 µs ± 591 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Boolean string operations can also be performed on ndarrays.

In [55]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

**Transpose**

In [56]:
sam2.shape = (3,3)
print(sam2, "\n")
print(sam2.T)

[[1 2 4]
 [2 3 0]
 [0 5 1]] 

[[1 2 0]
 [2 3 5]
 [4 0 1]]


**Data Types**


As previously mentioned, ndarrays can only have one data type. If we want to obtain or change this, we use the **.dtype** attribute.

In [58]:
sam2.dtype

dtype('int64')

What is the data type of the below ndarray?

In [59]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

What is the dtype of this array?

In [60]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)


What do you think has happened here?

In [61]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


In [62]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [63]:
ages_with_strings.size

126

In [64]:
ages_with_strings.size/21

6.0

In [65]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the .astype() method, demonstrated below

In [66]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


**Exercise-2**

 

In [68]:
#### Create an array of string numbers, but use dtype to make it an array of floats.

import numpy as np
X= ["3.4", "2.5", "6.2"]
Y = np.asarray(X, dtype=float)

print(X, type(X), type(X[0]))
print(Y, type(Y), type(Y[0]))

['3.4', '2.5', '6.2'] <class 'list'> <class 'str'>
[3.4 2.5 6.2] <class 'numpy.ndarray'> <class 'numpy.float64'>


In [69]:
#### Transpose the matrix, printing the new size and shape.
import numpy 
matrix=[[11,21,32],[41,53,64]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))

[[11, 21, 32], [41, 53, 64]]


[[11 41]
 [21 53]
 [32 64]]


In [70]:
print(type(matrix))

<class 'list'>


In [71]:
numpy.array(matrix, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

**Array Slicing Operations**


As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array.

In [72]:
five_times_table

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

In [73]:
five_times_table[0]

0

In [74]:
five_times_table[-1]

450

In [75]:
five_times_table[:4]

array([  0,  50, 100, 150])

In [76]:
five_times_table[4:]

array([200, 250, 300, 350, 400, 450])

We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

In [77]:
print(people)
people[:3, :3]

[[10]
 [ 5]
 [ 8]
 [32]
 [65]
 [43]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]


array([[10],
       [ 5],
       [ 8]])

**Exercise-2**


*   Create a numpy array with 50 zeros
*   Create a np array of 2 repeated 20 times
*   Create a numpy array from 0 to 2 pi  in steps of 0.1

For one of the arrays generated:

*   Get the first five values

*   Get the last 3 values

*  Get the 4th value to the 7th value   









In [78]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
np.repeat(2, 20)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [80]:
x = np.arange(start=0, stop=2*3.14, step=0.1)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [82]:
x[:5]



array([0. , 0.1, 0.2, 0.3, 0.4])

In [83]:
x[60:]

array([6. , 6.1, 6.2])

In [84]:
x[4:7]

array([0.4, 0.5, 0.6])

We can reverse an array by using .flip() or by using the :: operator.

In [85]:
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([450, 400, 350, 300, 250, 200, 150, 100,  50,   0])

In [86]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table

[450 400 350 300 250 200 150 100  50   0]


array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

We can also use the :: operator to select steps of the original array.

In [87]:
five_times_table[0::3] #Every 3rd element starting from 0

array([  0, 150, 300, 450])

**Exercise**

take one of the arrays you defined and

(*)#### Reverse it

(*)#### Only keep every 4th element.

(*)#### Get every 2nd element, starting from the last and moving backwards.



In [88]:
result = np.flip(x)

print("Reverse array",(result))

Reverse array [6.2 6.1 6.  5.9 5.8 5.7 5.6 5.5 5.4 5.3 5.2 5.1 5.  4.9 4.8 4.7 4.6 4.5
 4.4 4.3 4.2 4.1 4.  3.9 3.8 3.7 3.6 3.5 3.4 3.3 3.2 3.1 3.  2.9 2.8 2.7
 2.6 2.5 2.4 2.3 2.2 2.1 2.  1.9 1.8 1.7 1.6 1.5 1.4 1.3 1.2 1.1 1.  0.9
 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1 0. ]


In [89]:
x[4]

0.4

In [90]:
a = [2, 4, 6, 8, 10]
b = [2, 4, 6, 8, 10]
print( a[::2][::-1])
print (b[::2][::-1])

[10, 6, 2]
[10, 6, 2]


**Stats**

In [91]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [92]:
nums = np.arange(0, 4, 0.2555)

**Exercise**

Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [93]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


**Random**

With np.random, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [94]:
flip = np.random.choice([0,1], 10)
flip

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 1])

In [95]:
np.random.rand(10,20,9)

array([[[0.9654934 , 0.88864112, 0.52204519, ..., 0.78386979,
         0.74078411, 0.50698543],
        [0.46169535, 0.36972641, 0.88383421, ..., 0.83946774,
         0.17265883, 0.84289012],
        [0.02716596, 0.57200767, 0.03430285, ..., 0.24200156,
         0.80728998, 0.72742117],
        ...,
        [0.79956303, 0.13544087, 0.20391218, ..., 0.77835467,
         0.73524398, 0.90630502],
        [0.15707189, 0.51018889, 0.07642541, ..., 0.12435789,
         0.71268765, 0.23702043],
        [0.47474679, 0.8489927 , 0.61027009, ..., 0.30967353,
         0.70301803, 0.34475775]],

       [[0.74412726, 0.9391209 , 0.59685958, ..., 0.17074236,
         0.08429162, 0.90205044],
        [0.83644716, 0.47279694, 0.42478708, ..., 0.00473477,
         0.78242203, 0.12263366],
        [0.84539982, 0.59803185, 0.1822848 , ..., 0.4666599 ,
         0.02939345, 0.82115753],
        ...,
        [0.73158831, 0.24677384, 0.5106139 , ..., 0.46757961,
         0.86704163, 0.40808752],
        [0.5

In [96]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)

**Exercise**



* Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.


*   Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.



In [97]:
flip_for_die = np.random.choice([1,2,3,4,5,6], 10)
flip_for_die

array([3, 1, 6, 3, 3, 5, 6, 3, 2, 6])

In [98]:
coin=np.random.choice(['Head','Head','Tail'],10)

In [99]:
coin

array(['Head', 'Tail', 'Tail', 'Head', 'Tail', 'Head', 'Head', 'Head',
       'Head', 'Head'], dtype='<U4')